# Generated by Django 5.0.4 on 2024-05-07 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 1, 16, 59, 99184, tzinfo=datetime.timezone.utc), verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inserted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 1, 16, 59, 99184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='inserted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 1, 16, 59, 99184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 1, 16, 59, 100183, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='inserted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 1, 16, 59, 100183, tzinfo=datetime.timezone.utc)),
        ),
    ]
