# Generated by Django 5.0.4 on 2024-05-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
