# Generated by Django 5.0.4 on 2024-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
