# Generated by Django 5.0.4 on 2024-05-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
