# Generated by Django 5.1.3 on 2024-11-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_sale_cli_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
