# Generated by Django 5.1.3 on 2024-11-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_sale_cli_rename_inserted_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Products.cart'),
        ),
    ]
