# Generated by Django 5.1.3 on 2024-12-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
