# Generated by Django 5.1.3 on 2024-12-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_category_created_at_category_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.cart_item'),
        ),
    ]
