# Generated by Django 5.1.3 on 2024-12-10 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.cart'),
        ),
    ]
