# Generated by Django 5.1.3 on 2024-12-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='joys23services@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
